#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#

Name:       harbour-iwifi

# >> macros
# Neutralise the RPM BuildHost header so the build machine's hostname (and home
# network) never leak in a published package.
%define _buildhost localhost
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    The simple tool for WiFi networks analyzing
Version:    1.0.0
Release:    1
Group:      Qt/Qt
License:    GPLv3
URL:        https://github.com/JimKnopfIoT/harbour-iwifi
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   qt5-qtdeclarative-import-sensors
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Sensors)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  desktop-file-utils

%description
The simple tool for WiFi networks analyzing, distributed under GPLv3


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5

%qtc_make %{?_smp_mflags}

# >> build post
# Tier-3 monitor-mode sniffer: a standalone C program (raw AF_PACKET 802.11
# capture), built with the target gcc and installed as harbour-iwifi-sniff.
gcc -O2 -Wall -o helper/harbour-iwifi-sniff helper/iwsniff.c
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# Tier-3 monitor-mode pieces (app-gated; see harbour-iwifi-monitor.service):
install -D -m 755 helper/harbour-iwifi-sniff          %{buildroot}%{_bindir}/harbour-iwifi-sniff
install -D -m 755 helper/harbour-iwifi-monitor-up.sh  %{buildroot}%{_bindir}/harbour-iwifi-monitor-up.sh
install -D -m 755 helper/harbour-iwifi-monitor-down.sh %{buildroot}%{_bindir}/harbour-iwifi-monitor-down.sh
install -D -m 644 systemd/harbour-iwifi-monitor.service %{buildroot}%{_unitdir}/harbour-iwifi-monitor.service
install -D -m 644 data/50-harbour-iwifi-monitor.rules %{buildroot}%{_datadir}/polkit-1/rules.d/50-harbour-iwifi-monitor.rules
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%post
# Apply the new D-Bus policy and Sailjail permission without a reboot.
dbus-send --system --type=method_call --dest=org.freedesktop.DBus \
  / org.freedesktop.DBus.ReloadConfig >/dev/null 2>&1 || true
systemctl restart sailjaild >/dev/null 2>&1 || true

%files
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%config /etc/sailjail/permissions/WpaScan.permission
%config /etc/dbus-1/system.d/harbour-iwifi-wpa.conf
# >> files
%attr(755,root,root) %{_bindir}/harbour-iwifi-sniff
%attr(755,root,root) %{_bindir}/harbour-iwifi-monitor-up.sh
%attr(755,root,root) %{_bindir}/harbour-iwifi-monitor-down.sh
%{_unitdir}/harbour-iwifi-monitor.service
%{_datadir}/polkit-1/rules.d/50-harbour-iwifi-monitor.rules
# << files
